[ubuntu-docker]
docker1.irv.local


[ubuntu-docker:vars]
ansible_ssh_port=22
ansible_ssh_user=USER
ansible_ssh_pass=PASSWORD
ansible_become=yes
ansible_become_method=sudo
ansible_become_user=root
ansible_connection=ssh
