---
- name: set timezone
  shell: timedatectl set-timezone America/Toronto

- name: Install NTP
  apt: 
    name: ntp 
    state: present
  tags: ntp
 
- name: Copy over the NTP configuration
  copy: 
    src: ./templates/ntp.conf 
    dest: /etc/ntp.conf
  notify:
    - restart ntp
  tags: ntp
 
- name: Make sure NTP is stopped
  service: 
    name: ntp 
    state: stopped 
    enabled: yes
  tags: ntp
 
- name: Sync time initialy
  shell: ntpdate 192.168.0.15
  tags: ntp

- name: Make sure NTP is started up
  service: 
    name: ntp 
    state: started 
    enabled: yes
  tags: ntp

- name: Sync hwclock
  shell: hwclock -w
  tags: ntp